[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'michalbachowski/vim-wombat256mod'

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme tender
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline_theme = 'tender'
    let g:airline#extensions#virtualenv#enabled = 1
    set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    source $XDG_CONGIG_HOME/nvim/plugins/caw.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <Space>f :<C-u>NERDTreeToggle<CR>
    let NERDTreeIgnore = ['\.pyc$']
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nnoremap [figitive] <Nop>
    nnoremap <Leader>g [figitive]
    nnoremap <silent> [figitive]s :<C-u>Gstatus<CR>
    nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
    nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
    source $XDG_CONGIG_HOME/nvim/plugins/openbrowser.rc.vim
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    nnoremap <silent> <Leader>w :FixWhitespace<CR>
'''

[[plugins]]
repo = 'lambdalisue/vim-gista'
hook_add = '''
    let g:gista#client#default_username = 'm4ki02'
'''

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
    let g:previm_open_cmd = 'firefox'
'''

#[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
#repo = 'osyo-manga/vim-precious'
#depends = ['context_filetype.vim']

#[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
#repo = 'Shougo/context_filetype.vim'
